# SonarQube project properties

# Exclusions
sonar.exclusions=webpack.config.js,tsconfig.json,manifest.xml,jest.config.js,docs/**,sphinx-build/**,boms/**

# Default source code encoding
sonar.sourceEncoding=UTF-8